language: go

go:
  - 1.5
  - 1.6

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script: >
 go test $(go list ./... | grep -v /vendor/) -v -covermode=count -coverprofile=coverage.out
 $HOME/gopath/bin/goveralls -service=travis-ci